// .github/workflows/frontend.yml
name: Frontend CI/CD
on:
  push:
    paths:
      - 'frontend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t yourdockeruser/frontend:latest ./frontend
      - name: Push Docker image
        run: docker push yourdockeruser/frontend:latest
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker pull yourdockeruser/frontend:latest
            docker stop frontend || true && docker rm frontend || true
            docker run -d -p 80:80 --name frontend yourdockeruser/frontend:latest
