name: Build and Deploy Backend
on:
  push:
    paths:
      - 'project/backend/**'
jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app ./project/backend
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-app