name: Build and Deploy Frontend
on:
  push:
    branches:
      - main
    paths:
      - 'project/frontend/**'

jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app ./project/frontend

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app

      - name: SSH to VPS and deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-app
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker run -d -p 80:80 --name frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app

