name: Build and Deploy Frontend
on:
  push:
    paths:
      - 'project/frontend/**'
jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app ./project/frontend
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app